# Generated by Django 4.1.7 on 2023-07-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('address1', models.CharField(max_length=1024, verbose_name='Address line 1')),
                ('massege', models.CharField(max_length=1024)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agree', models.BooleanField()),
            ],
        ),
    ]
